server:
  port: 8080 #服务端口

spring:
  application:
    name: service-image-base64 #服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
          connection-timeout: 30000
          idle-timeout: 300000
          max-lifetime: 300000
          maximum-pool-size: 50
          minimum-idle: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cat.code.*.po